### ISSUE TITLE
incorrect plugins db name.

### ISSUE THREAD

**Issue by danmarsden** [CLAMP-IT/block_clampmail#65]
Your repository name should use the standard frankenstyle Moodle naming convention which makes it easy for moodle admins to identify your plugin.

the correct format to use is moodle-{frankenstylepluginname}
eg if your plugin was "mod_attendance" the correct name to use would be: "moodle-mod_attendance"

Github maintains redirects from your old name to the new one which makes this very easy - just hit the "settings" tab on your github repository and the rename repository option should appear near the top. 

I think this is also pretty important due to the nature of this plugin being a fork of another plugin.

**Comment by mackensen** [comment]
Done. I'm not sure why it was ever like that.
